-- Create enum type for user roles
CREATE TYPE user_role AS ENUM ('customer', 'staff', 'admin');

-- Create teams table
CREATE TABLE IF NOT EXISTS teams (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    description text,
    created_at timestamptz DEFAULT now()
);

-- Create user_roles table
CREATE TABLE IF NOT EXISTS user_roles (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES auth.users(id) UNIQUE,
    role user_role NOT NULL,
    team_id uuid REFERENCES teams(id),
    created_at timestamptz DEFAULT now()
);

-- Create tickets table
CREATE TABLE IF NOT EXISTS tickets (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    description text,
    status text NOT NULL,
    priority text NOT NULL,
    customer_email text NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    tags _text DEFAULT '{}'::text[],
    internal_notes text,
    assignee_id uuid REFERENCES auth.users(id),
    custom_fields jsonb DEFAULT '{}'::jsonb,
    resolved_at timestamptz,
    attachments jsonb DEFAULT '[]'::jsonb
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_tickets_customer_email ON tickets(customer_email);
CREATE INDEX IF NOT EXISTS idx_tickets_assignee ON tickets(assignee_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_user ON user_roles(user_id); 